name: Farset Labs
description: "Northern Ireland's Hackerspace"
tags: "hackerspace, makerspace, belfast, technology, maker movement"
pygments: true
markdown: kramdown
exclude: [README.md, _scripts, Gemfile, Gemfile.lock, etc, bin, makefile, buildout.cfg, bootstrap.py, requirements.txt]
plugins: ./_plugins
base: ""
gems:
  - jekyll-sitemap
paginate_path: "news/page:num"
paginate: 5
url: "http://www.farsetlabs.org.uk"
social:
  github: FarsetLabs
  facebook: FarsetLabs
  gplus: FarsetLabsOrgUk
  twitter: FarsetLabs
  flickr: groups/farset_labs
  blogfeed: "http://blog.farsetlabs.org.uk/feed/"
  forum: "http://discourse.farsetlabs.org.uk/"
links:
  - name: Blog
    url: "http://blog.farsetlabs.org.uk/"
  - name: Social
    url: ""
    list:
    - name: Facebook
      url: "http://facebook.com/FarsetLabs"
    - name: Twitter
      url: "http://twitter.com/FarsetLabs"
    - name: Forum
      url: "http://discourse.farsetlabs.org.uk/"
    - name: Flickr
      url: "http://www.flickr.com/groups/farset_labs"
    - name: Wiki
      url: "http://wiki.farsetlabs.org.uk/"
officers:
  - name: Andrew Bolster
    username: bolster
    year: 2011 -
    title: "Director/Founder"
    blurb: "Autonomous Systems Researcher, Consultant, Speaker, and Enfant Terrible. You can see some of his work over on [his website](http://andrewbolster.info)"
    email: "bolster@farsetlabs.org.uk"
    twitter: "bolster"
    website: "http://andrewbolster.info"
    facebook: "andrewbolster"
    linkedin: "andrewbolster"
    github: "andrewbolster"
    discourse: "bolster"

  - name: David Kane
    username: kane
    year: 2011 -
    title: "Director/Founder"
    blurb: "Physics student, photographer, electrical engineer and embedded developer, [among other things](http://www.davidkanecreative.co.uk/about.html)"
    email: "david@farsetlabs.org.uk"
    twitter: "dsrkane"
    discourse: "kane"

  - name: Dylan Wylie
    username: wylie
    year: 2013 -
    title: "Director"
    blurb: "Co-founder of rapidly growing health consultancy startup,  [We Slim Together](http://www.weslimtogether.co.uk), physicist, developer & technologist."
    email: "dylan@farsetlabs.org.uk"
    twitter: "dylwylie"
    discourse: "dylan"

  - name: Conor Robinson
    username: robinson
    year: 2014 -
    title: "Director"
    blurb: "Electrical and Electronic Engineer, Amateur Radio Course Tutor, Red Cross First Aider. Fixes stuff that's broken"
    email: "conor@farsetlabs.org.uk"
    discourse: "conor"
    linkedin: "conorrobinson"

  - name: Daniel Porter
    username: porter
    year: 2014 -
    title: "Digital Infrastructure NEM"
    email: "digitalinfrastructure@farsetlabs.org.uk"
    discourse: "stealthii"
    blurb: "Daniel makes the bits go around"
    twitter: "stealthii"
    github: "stealthii"

  - name: Glenn Davidson
    username: davidson
    year: 2014 -
    title: "Events NEM"
    blurb: "Glenn is an enthusiastic software engineer with 10 years experience in business problem analysis, enterprise systems, and mobile technology.  While currently working on cutting-edge start-up and mobile projects as part of [Coding Fury Ltd](http://www.codingfury.com/), he also organises local events for Ireland's independent game industry. Glenn is the central point of contact for Farsets event scheduling and logistics"
    email: "events@farsetlabs.org.uk"
    discourse: "panloaf"
    twitter: "glenndavidson"
    facebook: "panloaf"
    website: "http://blitter.co.uk"
    linkedin: "glennrdavidson"

  - name: Matt Hazely
    username: hazley
    year: 2015 -
    title: "Workshop NEM"
    email: "workshop@farsetlabs.org.uk"
    discourse: "matthazley"
    blurb: "music listener, beer maker, firmware engineer, podcaster"
    twitter: "matthazley"

  - name: Rachel Gregg
    username: gregg
    year: 2014 -
    title: "Community NEM"
    blurb: "Currently an Aeronautical Engineering Apprentice with [Bombardier](http://uk.bombardier.com), Rachel has a background in game testing, hospitality and  is the first point of contact for anything related to managing the community, or complaint handling"
    email: "community@farsetlabs.org.uk"
    discourse: "rachel_gregg"

  - name: Claire Wilgar
    username: wilgar
    year: 2014 -
    title: "Projects NEM"
    blurb: "Claire is a software developer at [Servasport](http://www.servasport.com/), and is the point of contact for resourcing and equipment issues related to member projects in the space."
    email: "projects@farsetlabs.org.uk"
    discourse: "clairebones"
    twitter: "clairedotw"

